app:
    resource: '@AppBundle/Controller/'
    type: annotation

account:
    resource: '@AppBundle/Controller/AccountController.php'
    type: annotation
    prefix: /account

artists:
    resource: '@AppBundle/Controller/ArtisteController.php'
    type: annotation
    prefix: /artists

albums:
    resource: '@AppBundle/Controller/AlbumController.php'
    type: annotation
    prefix: /albums

logout:
    path: /account/logout