# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database:
            entity:
              class: AppBundle:Abonne
              property: login

    encoders:
      AppBundle\Entity\Abonne: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /account/login
                check_path: /account/login
            logout:
                path: /account/logout
                target: homepage
            provider: database

    access_control:
      - { path: ^/account/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/account, roles: IS_AUTHENTICATED_FULLY }
